### ISSUE TITLE
antd版使用useModal的时候，里面的配置有些是无效的

### ISSUE THREAD

**Issue by san346596324** [jekip/naive-ui-admin#68]
![V$PVQOCXOK0MLE0U~VAWE$A](https://user-images.githubusercontent.com/30828520/142091302-22b2e064-30a0-441a-8a3a-2179d0356220.png)
比如：maskClosable，写了true，点背景还是无法关闭弹窗

**Comment by 2462870727** [comment]
你好 antd版本是哪个，能否发给我看看

**Comment by jekip** [comment]
> 你好 antd版本是哪个，能否发给我看看

https://www.naiveadmin.com 这里有介绍和预览地址

**Comment by 2462870727** [comment]
> > 你好 antd版本是哪个，能否发给我看看
> 
> https://www.naiveadmin.com 这里有介绍和预览地址

存在这个问题吗 项目代码在哪个仓库

**Comment by jekip** [comment]
antd版本是商业版，没有开源

**Comment by 2462870727** [comment]
好的 我还想试着修复一下这个问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jekip/naive-ui-admin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月17日(星期三) 下午3:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jekip/naive-ui-admin] antd版使用useModal的时候，里面的配置有些是无效的 (Issue #68)





 
antd版本是商业版，没有开源
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jekip** [comment]
已解决
